# Generated by Django 3.0.3 on 2020-03-14 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200306_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='l_heading_text',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='article',
            name='s_heading_text',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
